// PASTE THIS AT THE END OF: app/static/js/dashboard.js

let currentVerification={transactionId:null,riskTier:null,challengePhrase:null,otpCode:null,expiresAt:null};
let challengeMediaRecorder=null,challengeAudioChunks=[],challengeRecordingTimer=null,challengeSeconds=0;

function showVerificationModal(data){currentVerification={transactionId:data.transaction_id,riskTier:data.risk_tier,challengePhrase:data.challenge_phrase||null,otpCode:data.otp_code||null,expiresAt:data.expires_at};const modal=document.getElementById('verifyModal'),otpCard=document.getElementById('otpCard'),challengeCard=document.getElementById('challengeCard'),description=document.getElementById('verifyDescription');otpCard.classList.add('hidden');challengeCard.classList.add('hidden');if(data.risk_tier==='MEDIUM'){description.textContent='Enter the 6-digit code';otpCard.classList.remove('hidden');if(data.otp_code)document.getElementById('otpDisplay').innerHTML=`Code: <span class="font-mono text-lg text-indigo-400">${data.otp_code}</span>`;const otpInput=document.getElementById('otpInput');otpInput.value='';setTimeout(()=>otpInput.focus(),300)}else if(data.risk_tier==='HIGH'){description.textContent='Speak the phrase';challengeCard.classList.remove('hidden');document.getElementById('challengePhrase').textContent=data.challenge_phrase}startExpiryCountdown(data.expires_at);modal.classList.remove('hidden');modal.classList.add('flex')}

function closeVerifyModal(){document.getElementById('verifyModal').classList.add('hidden');if(challengeMediaRecorder&&challengeMediaRecorder.state==='recording')challengeMediaRecorder.stop();clearInterval(challengeRecordingTimer)}

async function submitOTP(){const otpInput=document.getElementById('otpInput').value.trim();if(!otpInput||otpInput.length!==6){showXaiAlert('error','Invalid','Enter 6 digits',{});return}const formData=new FormData();formData.append('transaction_id',currentVerification.transactionId);formData.append('otp_code',otpInput);const response=await fetch('/api/v1/transactions/verify',{method:'POST',credentials:'include',body:formData});const result=await response.json();if(response.ok&&result.success){closeVerifyModal();showXaiAlert('success','Verified','Approved!',{});await loadTransactions()}else{showXaiAlert('error','Failed','Invalid code',{})}}

async function startChallengeRecording(){const stream=await navigator.mediaDevices.getUserMedia({audio:true});challengeAudioChunks=[];challengeMediaRecorder=new MediaRecorder(stream);challengeMediaRecorder.ondataavailable=e=>{if(e.data.size>0)challengeAudioChunks.push(e.data)};challengeMediaRecorder.onstop=async()=>{const audioBlob=new Blob(challengeAudioChunks,{type:'audio/webm'});await submitChallengeAudio(audioBlob);stream.getTracks().forEach(t=>t.stop())};challengeMediaRecorder.start();document.getElementById('startChallengeBtn').classList.add('hidden');document.getElementById('stopChallengeBtn').classList.remove('hidden');document.getElementById('challengeRecordingTimer').classList.remove('hidden');challengeSeconds=0;challengeRecordingTimer=setInterval(()=>{challengeSeconds++;document.getElementById('challengeTimerDisplay').textContent=`${String(Math.floor(challengeSeconds/60)).padStart(2,'0')}:${String(challengeSeconds%60).padStart(2,'0')}`;if(challengeSeconds>=10)stopChallengeRecording()},1000)}

function stopChallengeRecording(){if(challengeMediaRecorder&&challengeMediaRecorder.state==='recording')challengeMediaRecorder.stop();clearInterval(challengeRecordingTimer);document.getElementById('startChallengeBtn').classList.remove('hidden');document.getElementById('stopChallengeBtn').classList.add('hidden');document.getElementById('challengeRecordingTimer').classList.add('hidden')}

async function submitChallengeAudio(audioBlob){const formData=new FormData();formData.append('transaction_id',currentVerification.transactionId);formData.append('audio_file',audioBlob,'challenge.webm');showXaiAlert('warning','Processing','Verifying...',{});const response=await fetch('/api/v1/transactions/verify',{method:'POST',credentials:'include',body:formData});const result=await response.json();if(response.ok&&result.success){closeVerifyModal();showXaiAlert('success','Verified','Voice passed!',{});await loadTransactions()}else{showXaiAlert('error','Failed','Voice did not match',{})}}

function startExpiryCountdown(expiresAt){const expiryTime=new Date(expiresAt);const update=()=>{const remaining=Math.max(0,expiryTime-new Date());if(remaining===0){closeVerifyModal();showXaiAlert('error','Expired','Window closed',{});return}const mins=Math.floor(remaining/60000),secs=Math.floor((remaining%60000)/1000);document.getElementById('verifyExpiry').textContent=`${mins}:${String(secs).padStart(2,'0')}`};update();setInterval(update,1000)}
